version: '3'
services:
  # api:
  #   container_name: full_api
  #   build: .
  #   env_file:
  #     - env/application.env
  #   ports: 
  #     - 8080:8080 
  #   restart: on-failure
  #   volumes:
  #     - api:/usr/src/api/
  #   depends_on:
  #     - fullstack-postgres          
  #   networks:
  #     - fullstack

  fullstack-postgres:
    image: postgres:latest
    container_name: full_db_postgres
    env_file:
      - env/application.env
    environment:
      - POSTGRES_USER=${DATABASE_USER}  
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack

volumes:
  api:
  database_postgres:                  

networks:
  fullstack:
    driver: bridge
